user_command_list = [
    # 30 LLM-related questions
    "Explain the difference between GPT-3 and GPT-4.",
    "What are the common use cases of large language models?",
    "Can LLMs understand context in conversation?",
    "How do LLMs handle ambiguity in language?",
    "What's the architecture behind GPT?",
    "What datasets are used to train language models?",
    "Explain the concept of 'fine-tuning' in LLMs.",
    "Can LLMs generate human-like text?",
    "How do you reduce bias in language models?",
    "What is zero-shot learning in LLMs?",
    "How do transformers work in LLMs?",
    "What are the challenges with training large language models?",
    "How can LLMs improve over time?",
    "Can LLMs generate code?",
    "What is the role of attention mechanisms in LLMs?",
    "How does tokenization work in LLMs?",
    "How do language models understand slang or idioms?",
    "What are the ethical concerns regarding LLMs?",
    "Can LLMs be used for sentiment analysis?",
    "How do LLMs differ from traditional NLP models?",
    "What is 'transfer learning' in the context of LLMs?",
    "How can LLMs be used for text summarization?",
    "Can LLMs answer factual questions accurately?",
    "What limitations do LLMs currently have?",
    "How are hallucinations handled in LLM outputs?",
    "Can LLMs translate languages?",
    "What is 'prompt engineering' in LLMs?",
    "Can you explain the training process of LLMs?",
    "How does an LLM learn from context?",
    "What future advancements do you predict for LLMs?",

    # 30 VR/XR-related questions
    "What is the difference between VR and AR?",
    "How does haptic feedback work in VR?",
    "What are the main challenges in VR development?",
    "Can VR be used for medical training?",
    "What is the role of spatial audio in VR?",
    "How can VR enhance gaming experiences?",
    "What is extended reality (XR)?",
    "How do VR headsets track motion?",
    "What are some popular VR game engines?",
    "What are the safety concerns with using VR for extended periods?",
    "How can VR be used in education?",
    "What’s the future of social interaction in VR?",
    "How does positional tracking work in VR systems?",
    "What role does AI play in enhancing VR experiences?",
    "Can VR replicate real-world physics?",
    "How can VR be used for therapeutic purposes?",
    "What are the limitations of current VR technology?",
    "How does eye tracking improve VR interactions?",
    "What is foveated rendering in VR?",
    "How can VR be used in architectural visualization?",
    "Can VR environments be customized by users?",
    "How does latency impact VR experiences?",
    "What is the role of controllers in VR systems?",
    "Can VR help simulate dangerous job training?",
    "How does VR affect the human brain?",
    "What is the impact of resolution on immersion in VR?",
    "How can VR improve remote collaboration?",
    "What is the importance of field of view in VR?",
    "How are virtual avatars used in VR social spaces?",
    "What are the main industries benefiting from VR technology?",

    # 40 general commands
    "Start the simulation.",
    "Take me to the main menu.",
    "Activate voice commands.",
    "Turn on night mode.",
    "Pause the game.",
    "Save my current progress.",
    "Open the settings menu.",
    "Change my avatar.",
    "Load the last checkpoint.",
    "Show me a tutorial.",
    "Enable subtitles.",
    "Switch to third-person view.",
    "Adjust the volume.",
    "Increase the brightness.",
    "Show me my inventory.",
    "Equip my last-used weapon.",
    "Show me a map of the area.",
    "Zoom in on the target.",
    "Enable VR mode.",
    "Play background music.",
    "Mute the voice chat.",
    "Show me my health status.",
    "Teleport to the next location.",
    "Undo the last action.",
    "Take a screenshot.",
    "Enable haptic feedback.",
    "Change the language settings.",
    "Turn on the flashlight.",
    "Access my achievements.",
    "Display the leaderboard.",
    "Switch to AR mode.",
    "Display the time.",
    "Highlight interactable objects.",
    "Perform a quick save.",
    "Open the help menu.",
    "Show me my quest log.",
    "Skip the current scene.",
    "Recalibrate the sensors.",
    "Exit the current simulation.",
    "Show the camera feed."
]


# print(len(user_command_list))
